#!/bin/bash

# Download RetroArch thumbnails only for selected platforms.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
. "$SCRIPT_DIR/retro_setup_common.sh"

selected_platforms_or_all
load_url_config

THUMB_DIR="$RA_DIR/thumbnails"
PLAYLIST_DIR="$RA_DIR/playlists"
BASE_URL="${THUMBNAILS_BASE_URL:-https://thumbnails.libretro.com}"
TYPES=("Named_Boxarts" "Named_Snaps" "Named_Titles")

UA="Mozilla/5.0 (X11; Linux) AppleWebKit/537.36 (KHTML, like Gecko) Chrome Safari"
WGET_OPTS=(
    --user-agent="$UA"
    --continue
    --tries=2
    --waitretry=2
    --timeout=15
    --retry-connrefused
    --show-progress
)

if command -v wget >/dev/null 2>&1 && wget --help 2>/dev/null | grep -q -- '--retry-on-http-error'; then
    WGET_OPTS+=(--retry-on-http-error=429,500,502,503,504)
fi

mkdir -p "$THUMB_DIR"

url_encode_component() {
    local value="$1"
    if command -v python3 >/dev/null 2>&1; then
        python3 -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1], safe=""))' "$value"
    else
        printf '%s' "$value" | sed 's/%/%25/g; s/ /%20/g; s/#/%23/g; s/&/%26/g; s/+/%2B/g'
    fi
}

playlist_labels() {
    local playlist="$1"
    if command -v python3 >/dev/null 2>&1; then
        python3 -c 'import json, sys
with open(sys.argv[1], encoding="utf-8") as source:
    for item in json.load(source).get("items", []):
        label = item.get("label")
        if isinstance(label, str) and label:
            sys.stdout.buffer.write(label.encode("utf-8") + b"\0")' "$playlist"
    else
        # Playlists generated by retro_setup keep one JSON label per line.
        sed -n 's/^[[:space:]]*"label": "\(.*\)",[[:space:]]*$/\1/p' "$playlist" |
            while IFS= read -r label; do printf '%s\0' "$label"; done
    fi
}

thumbnail_name() {
    # RetroArch/libretro replaces filesystem-invalid characters in thumbnail names.
    printf '%s' "$1" | sed 's#[&*/:`<>?|\\]#_#g'
}

normalize_goodtools_label() {
    local value="$1"
    value="$(printf '%s' "$value" | sed \
        -e 's/\[[^]]*\]//g' \
        -e 's/(U)/(USA)/g' -e 's/(E)/(Europe)/g' -e 's/(J)/(Japan)/g' \
        -e 's/(W)/(World)/g' -e 's/(F)/(France)/g' -e 's/(G)/(Germany)/g' \
        -e 's/(I)/(Italy)/g' -e 's/(S)/(Spain)/g' -e 's/(K)/(Korea)/g' \
        -e 's/(C)/(China)/g' -e 's/(A)/(Australia)/g' -e 's/(B)/(Brazil)/g' \
        -e 's/(VC)/(Virtual Console)/g' \
        -e 's/[[:space:]][[:space:]]*/ /g' -e 's/[[:space:]]*$//')"
    printf '%s' "$value"
}

download_thumbnail() {
    local system="$1"
    local type="$2"
    local label="$3"
    local system_encoded filename remote_filename filename_encoded url dest

    system_encoded="$(url_encode_component "$system")"
    filename="$(thumbnail_name "$label").png"
    remote_filename="$(thumbnail_name "$(normalize_goodtools_label "$label")").png"
    filename_encoded="$(url_encode_component "$remote_filename")"
    url="${BASE_URL%/}/$system_encoded/$type/$filename_encoded"
    dest="$THUMB_DIR/$system/$type/$filename"

    mkdir -p "$(dirname "$dest")"
    if [ -s "$dest" ]; then
        skipped=$((skipped + 1))
    elif wget "${WGET_OPTS[@]}" --quiet --output-document="$dest.part" "$url"; then
        mv -f "$dest.part" "$dest"
        downloaded=$((downloaded + 1))
        echo "Downloaded: $system / $type / $label"
    else
        rm -f "$dest.part"
        missing=$((missing + 1))
        echo "IMAGE NOT FOUND: $system / $type / $label"
    fi
}

if ! command -v wget >/dev/null 2>&1; then
    install_tool_package wget wget wget wget wget wget
fi

echo "=== Starting Thumbnail Download ==="
echo "Base URL: ${BASE_URL%/}"

downloaded=0
skipped=0
missing=0
platforms_without_roms=0

for platform in "${SELECTED_PLATFORMS[@]}"; do
    system="${PLATFORM_NAME[$platform]}"
    playlist="$PLAYLIST_DIR/$system.lpl"

    if [ ! -f "$playlist" ]; then
        echo "NO ROMS FOUND: $system (playlist was not generated: $playlist)."
        platforms_without_roms=$((platforms_without_roms + 1))
        continue
    fi

    labels=()
    while IFS= read -r -d '' label; do labels+=("$label"); done < <(playlist_labels "$playlist")
    if [ "${#labels[@]}" -eq 0 ]; then
        echo "NO ROMS FOUND: $system ($playlist contains no games)."
        platforms_without_roms=$((platforms_without_roms + 1))
        continue
    fi

    echo "--- Processing System: $system (${#labels[@]} ROMs) ---"

    for type in "${TYPES[@]}"; do
        for label in "${labels[@]}"; do
            download_thumbnail "$system" "$type" "$label"
        done
    done
done

echo "=== Thumbnail Download Complete: $downloaded downloaded, $skipped existing, $missing images not found, $platforms_without_roms systems without ROMs ==="
